name: Production Multi-Tier Cloud Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Ship Platform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Codebase
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Terraform Core
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      # NEW SAFETY EXTRACTION: Validates architecture logic compilation upfront
      - name: Terraform Guardrail Validations
        run: |
          cd terraform/environments/dev
          terraform init
          terraform validate

      - name: Import Existing AWS Resources
        run: |
          cd terraform/environments/dev
          terraform import -var="db_password=${{ secrets.DB_PASSWORD }}" -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" 'module.security.aws_iam_role.ecs_execution_role' fintech-ecs-execution-role-dev || true
          terraform import -var="db_password=${{ secrets.DB_PASSWORD }}" -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" 'module.frontend.aws_s3_bucket.frontend' fintech-platform-ui-dev-${{ secrets.DOCKERHUB_USERNAME }} || true
          terraform import -var="db_password=${{ secrets.DB_PASSWORD }}" -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" 'module.compute.aws_lb.main' arn:aws:elasticloadbalancing:eu-west-1:224039895487:loadbalancer/app/fintech-alb-dev/617f7a4d7362613d || true
          terraform import -var="db_password=${{ secrets.DB_PASSWORD }}" -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" 'module.compute.aws_lb_target_group.transaction' arn:aws:elasticloadbalancing:eu-west-1:224039895487:targetgroup/tg-transaction-dev/ebf22919282aa0c5 || true
          terraform import -var="db_password=${{ secrets.DB_PASSWORD }}" -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" 'module.compute.aws_lb_target_group.fraud' arn:aws:elasticloadbalancing:eu-west-1:224039895487:targetgroup/tg-fraud-dev/981da6df45f7d17c || true
          terraform import -var="db_password=${{ secrets.DB_PASSWORD }}" -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" 'module.compute.aws_lb_target_group.wallet' arn:aws:elasticloadbalancing:eu-west-1:224039895487:targetgroup/tg-wallet-dev/c1d51b5e68b9b480 || true

      - name: Terraform Deploy Infrastructure
        id: terraform
        run: |
          cd terraform/environments/dev
          terraform apply -auto-approve \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Extract Deployment Target URLs
        id: outputs
        run: |
          cd terraform/environments/dev
          echo "ALB_URL=$(terraform output -raw backend_api_gateway_url)" >> $GITHUB_OUTPUT
          echo "S3_BUCKET=$(terraform output -raw live_web_ui_url | sed 's/http:\/\///' | cut -d'.' -f1)" >> $GITHUB_OUTPUT

      - name: Build & Publish Microservices
        run: |
          cd services/transaction-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/transaction-service:v1 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/transaction-service:v1
          
          cd ../fraud-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fraud-service:v1 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fraud-service:v1
          
          cd ../wallet-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wallet-service:v1 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wallet-service:v1

      - name: Compile Web Dashboard UI
        env:
          REACT_APP_API_URL: ${{ steps.outputs.outputs.ALB_URL }}
        run: |
          cd frontend/react-app
          npm install
          npm run build

      - name: Sync UI Assets to AWS S3 Static Bucket
        run: |
          aws s3 sync frontend/react-app/build/ s3://${{ steps.outputs.outputs.S3_BUCKET }} --delete